### PR TITLE
Compatibility python 3.8

### PR DESCRIPTION
**Pull request by arakeis**
this made the project able to be installed on my ubuntu/mint linux desktop,
minor changes

### CODE REVIEW

**Comment by deufrai** [comment]
Many thanks for this
The requirements file is a very sensitive place, as we are aiming at running on 4 hardware platforms. 
Will look into it eventually

**Comment by arakeis** [comment]
Yes of course
Will try to cross check on my raspberry!

Le lun. 1 mars 2021 à 17:24, Frederic CORNU <notifications@github.com> a
écrit :

**Comment by deufrai** [comment]
trouble ?

**Comment by arakeis** [comment]
Yes, wrongly comited against the 0.7 branch instead of the develop branch.

Will test the raspberry version tomorow and then the working PR (fingers
crossed)

Le lun. 1 mars 2021 à 19:34, Frederic CORNU <notifications@github.com> a
écrit :

**Pull request closed without merging**
