### PR TITLE
Alpha: Implementation of wavelets

### PR DESCRIPTION
**Pull request by gnthibault**
New dependency: dtcwt package
Can someone try it on his/her computer and tell me if it works @dragonlost  @gehelem ?

### CODE REVIEW

**Comment by gehelem** [comment]
I had to install dtcwt
Can you update readme ?

**Comment by dragonlost** [comment]
please no multiply librairy : use opencv for convert rgb to hsv 
exemple : 
hsv_img = cv2.cvtColor(img, cv2.COLOR_RGB2HSV)

**Comment by gnthibault** [comment]
That was actually already done like this, I just forgot an import. Now fixed

**Comment by gnthibault** [comment]
Now there are conflicts, can we please validate the PR or just close it ?

**Comment by gnthibault** [comment]
Thank you ;)

**Pull request merged**
